file_format: "1"
id: zboard
name: Zboard
type: shield
url: https://github.com/oldmanz/zboard
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - zboard_left
  - zboard_right